### ISSUE TITLE
Loading MFCC (.mfc HTK generated file)

### ISSUE THREAD

**Issue by jvel07** [danijel3/PyHTK#3]
Hi! Congrats for your work, it is superb.
I am trying to load a .mfc file generated by HTK Tools, and when I do this:
> from HTK import HTKFile
> htk = HTKFile()
> htk.load('devel_0001.mfc')

The following error shows up: Traceback (most recent call last):
  File "/Users/PycharmProjects/speech_mfcc/test2.py", line 5, in <module>
    htk.load('j_htk/devel_0001.mfc')
  File "/Users/PycharmProjects/speech_mfcc/HTK.py", line 142, in load
    s = f.read(self.nFeatures * 4)
ValueError: read length must be positive or -1

Am I missing something?
Thanks!

**Comment by danijel3** [comment]
Can you post the file somewhere? I would need to analyze the file to know for sure.

**Comment by jvel07** [comment]
Sure, this is the link to the file:
https://1drv.ms/u/s!AugEGb8Co6hBjkr5vk-fndOhgVMP

**Comment by danijel3** [comment]
Ok, seems like something may have changed in HTK and the file format is slightly different. I'm pretty sure all the words used to be big-endian cause I used this code many times and it simply worked. Your file uses little-endian which would normally make sense, as that is the native ordering on Intel PCs, however with HTK it was always the other way around (probably due to some legacy compatibility issue).

In this [line](https://github.com/danijel3/PyHTK/blob/f94b0ed4e689d22b632a02e24afd3b7491384da5/python/HTK.py#L69) I added a simple check to see if the values extracted from the header make sense. If they don't, i simple reverse the endianess and try again. It's not a super-duper 100% solution, but it should be fine for 99.999% cases. I guess if someone makes an empty file, this check won't work...

In any case, please lemme know if this fix works and close the issue when you're satisfied.

**Comment by jvel07** [comment]
Thanks so much, it seems to be working fine. :) I'll let you know if any issue shows up.
